package arrays;
import java.util.Scanner;

public class Main {
    public static void main(String[] args) {
        String[] newArr = new String[5];
        newArr[0] = "hello";
        newArr[1] = "hi";
        newArr[2] = "time";
        newArr[3] = "bye";
        newArr[4] = "bill";

        int[] nums = {2,4,45,6,8};
        int y = nums[4];
        double [] nums2 = {3.6, 4.5};
        String x = newArr[1];
        System.out.println(x);
        System.out.println(y);
    }
}
